# Represent Collected Data in Table Format

In [2]:
import pandas as pd
from nwi_cities import NWI_CITIES

# Convert the dictionary to a DataFrame
df_cities = pd.DataFrame.from_dict(NWI_CITIES, orient="index")
df_cities.reset_index(inplace=True)
df_cities.rename(columns={"index": "City"}, inplace=True)
df_cities["Coordinates"] = df_cities.apply(
    lambda row: f"({row['lat']}, {row['lng']})", axis=1
)

# Select and order the columns for display
columns = [
    "City",
    "Coordinates",
    "population",
    "fips_code",
    "county",
    "fast_food_percentage",
    "median_income",
]
df_cities = df_cities[columns]

# Display the DataFrame
df_cities

,City,Coordinates,population,fips_code,county,fast_food_percentage,median_income
0,Cedar Lake,"(41.3647578, -87.4411473)",13725,1811062,Lake County,0.3667,73611
1,Crown Point,"(41.4169806, -87.3653136)",33518,1816138,Lake County,0.3500,87500
2,Dyer,"(41.4942021, -87.5217068)",16422,1819270,Lake County,0.3667,90848
3,East Chicago,"(41.6397857, -87.4548466)",26502,1819486,Lake County,0.3333,37807
4,Gary,"(41.6020962, -87.3370646)",69739,1827000,Lake County,0.5179,34085
5,Griffith,"(41.534507, -87.4255305)",16213,1830042,Lake County,0.5500,64265
6,Hammond,"(41.5833618, -87.5000081)",77491,1831000,Lake County,0.6167,48107
7,Highland,"(41.5536529, -87.4520484)",23695,1833466,Lake County,0.6000,71246
8,Hobart,"(41.5322592, -87.2550353)",29516,1834114,Lake County,0.4500,63168
9,Lake Station,"(41.5750369, -87.2389246)",13292,1841535,Lake County,0.4833,50852
10,Lowell,"(41.2914244, -87.4205903)",10569,1845144,Lake County,0.4333,71463
11,Merrillville,"(41.4828144, -87.3328139)",36196,1848528,Lake County,0.4167,61230
12,Munster,"(41.5644798, -87.5125412)",23717,1851912,Lake County,0.6167,96938
13,Saint John,"(41.45, -87.47)",19805,1866852,Lake County,0.4167,115230
14,Schererville,"(41.4789246, -87.4547605)",29381,1868220,Lake County,0.3833,77530
15,Whiting,"(41.6797578, -87.4944873)",4571,1884122,Lake County,0.4000,50590
16,Beverly Shores,"(41.6925381, -86.9775319)",588,1805158,Porter County,0.0000,104063
17,Burns Harbor,"(41.6258708, -87.1333676)",2374,1809370,Porter County,0.4333,87396
18,Chesterton,"(41.6105938, -87.0641992)",14045,1812412,Porter County,0.3500,86098
19,Hebron,"(41.3186482, -87.2003091)",3397,1832818,Porter County,0.5000,64276
20,Kouts,"(41.3167058, -87.0258594)",2311,1840518,Porter County,0.5000,65987
21,Ogden Dunes,"(41.6228148, -87.1917022)",1198,1856088,Porter County,0.3214,134250
22,Portage,"(41.5758708, -87.1761455)",37540,1861092,Porter County,0.5167,63550
23,Porter,"(41.6164, -87.0748)",5175,1861164,Porter County,0.3500,79247
24,South Haven,"(41.5429357, -87.1395051)",4717,1871288,Porter County,0.4746,59271
25,Valparaiso,"(41.4730948, -87.0611412)",33820,1878326,Porter County,0.3667,56465